# docker-compose.yml
version: '3.5'
services:
  database:
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_DB=postgre
    ports:
      - 5432:5432
    volumes:
      - ./data-postgre:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose